version: '3.8'
services:
  # Jaeger
  otel-jaeger-all-in-one:
    image: jaegertracing/all-in-one:1.47
    ports:
      - "16686:16686"
      - "14268"
      - "14250"
    networks:
      - tyk
  # Collector
  otel-collector-gateway:
    image: otel/opentelemetry-collector:0.81.0
    volumes:
      - ./deployments/otel/confs/otel-collector.yml:/etc/otel-collector.yml
    command: [ "--config=/etc/otel-collector.yml" ]
    ports:
      - "1888:1888"   # pprof extension
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP http receiver
      - "55670:55679" # zpages extension
    depends_on:
      - otel-jaeger-all-in-one
    networks:
      - tyk

networks:
  tyk: